plugin:
  - changed-files:
    - any-glob-to-any-file: plugin/**

server:
  - changed-files:
    - any-glob-to-any-file: server/**

proto:
  - changed-files:
    - any-glob-to-any-file: proto/**

ssh:
  - changed-files:
    - any-glob-to-any-file: plugin/src/ssh/**

ui:
  - changed-files:
    - any-glob-to-any-file: plugin/src/ui/**

settings:
  - changed-files:
    - any-glob-to-any-file: plugin/src/settings/**

adapter:
  - changed-files:
    - any-glob-to-any-file: plugin/src/adapter/**

cache:
  - changed-files:
    - any-glob-to-any-file: plugin/src/cache/**

tests:
  - changed-files:
    - any-glob-to-any-file: plugin/tests/**
    - any-glob-to-any-file: server/**/*_test.go

dependencies:
  - changed-files:
    - any-glob-to-any-file: plugin/package.json
    - any-glob-to-any-file: plugin/package-lock.json
    - any-glob-to-any-file: server/go.mod
    - any-glob-to-any-file: server/go.sum

ci:
  - changed-files:
    - any-glob-to-any-file: .github/**

build:
  - changed-files:
    - any-glob-to-any-file: plugin/esbuild.config.mjs
    - any-glob-to-any-file: plugin/tsconfig.json
    - any-glob-to-any-file: server/Makefile
